// HudumaCare Redesign — shared data
const FACILITIES = [
  {
    id: 'agakhan-westlands',
    name: 'Aga Khan University Hospital',
    type: 'Hospital — Level 6',
    ownership: 'private',
    category: 'general',
    address: '3rd Parklands Avenue, Limuru Road',
    county: 'Nairobi', subcounty: 'Westlands',
    coords: { lat: -1.2655, lng: 36.808 },
    phone: '+254 20 366 2000',
    whatsapp: '+254 711 092 000',
    email: 'info@aku.edu',
    verified: 'regulator_verified',
    rating: 4.6, reviewCount: 832,
    distanceKm: 3.2,
    insurance: ['NHIF', 'AAR', 'JUBILEE', 'CIC', 'BRITAM', 'OLDMUTUAL'],
    services: ['Cardiology', 'Maternity', 'Lab', 'Imaging', 'Emergency 24/7', 'Pharmacy'],
    open: true, openLabel: 'Open 24 hours',
    photo: 'hospital',
    priceBand: 'KSh',
    waitMins: 35,
  },
  {
    id: 'mp-shah',
    name: 'M.P. Shah Hospital',
    type: 'Hospital — Level 5',
    ownership: 'faith_based',
    category: 'general',
    address: 'Shivachi Road, Parklands',
    county: 'Nairobi', subcounty: 'Westlands',
    coords: { lat: -1.262, lng: 36.815 },
    phone: '+254 20 429 1000', whatsapp: '+254 722 204 411',
    email: 'info@mpshahhosp.org',
    verified: 'facility_claimed',
    rating: 4.4, reviewCount: 612,
    distanceKm: 2.8,
    insurance: ['NHIF', 'AAR', 'JUBILEE', 'MADISON', 'BRITAM'],
    services: ['Maternity', 'Surgery', 'Lab', 'Imaging', 'Emergency'],
    open: true, openLabel: 'Open until 22:00',
    photo: 'hospital',
    priceBand: 'KSh',
    waitMins: 22,
  },
  {
    id: 'pathcare-kenya',
    name: 'PathCare Kenya — Westlands Branch',
    type: 'Laboratory',
    ownership: 'private',
    category: 'lab',
    address: 'Sarit Centre, Westlands',
    county: 'Nairobi', subcounty: 'Westlands',
    coords: { lat: -1.267, lng: 36.804 },
    phone: '+254 709 904 000', whatsapp: '+254 709 904 000',
    verified: 'facility_claimed',
    rating: 4.7, reviewCount: 218,
    distanceKm: 1.4,
    insurance: ['NHIF', 'AAR', 'JUBILEE', 'CIC', 'BRITAM', 'APA', 'MADISON'],
    services: ['Blood tests', 'Urinalysis', 'Home sample collection', 'PCR'],
    open: true, openLabel: 'Open until 19:00',
    photo: 'lab',
    priceBand: 'KSh',
    waitMins: 8,
  },
  {
    id: 'family-dental',
    name: 'Family Dental Centre',
    type: 'Dental Clinic',
    ownership: 'private',
    category: 'dental',
    address: 'ABC Place, Waiyaki Way',
    county: 'Nairobi', subcounty: 'Westlands',
    coords: { lat: -1.268, lng: 36.795 },
    phone: '+254 733 600 600', whatsapp: '+254 733 600 600',
    verified: 'community_verified',
    rating: 4.5, reviewCount: 96,
    distanceKm: 4.1,
    insurance: ['NHIF', 'AAR', 'JUBILEE'],
    services: ['Cleaning', 'Fillings', 'Root canal', 'Orthodontics'],
    open: false, openLabel: 'Opens tomorrow 09:00',
    photo: 'clinic',
    priceBand: 'KSh',
    waitMins: 15,
  },
  {
    id: 'metropolitan-pharmacy',
    name: 'Metropolitan Pharmacy',
    type: 'Pharmacy',
    ownership: 'private',
    category: 'pharmacy',
    address: 'Yaya Centre, Argwings Kodhek',
    county: 'Nairobi', subcounty: 'Kilimani',
    coords: { lat: -1.295, lng: 36.785 },
    phone: '+254 711 023 000', whatsapp: '+254 711 023 000',
    verified: 'regulator_verified',
    rating: 4.3, reviewCount: 144,
    distanceKm: 5.6,
    insurance: ['NHIF', 'AAR', 'BRITAM', 'CIC'],
    services: ['Prescriptions', 'Wellness', 'Home delivery', 'Vaccination'],
    open: true, openLabel: 'Open until 22:00',
    photo: 'pharmacy',
    priceBand: 'KSh',
    waitMins: 5,
  },
  {
    id: 'nairobi-women',
    name: "Nairobi Women's Hospital — Hurlingham",
    type: 'Maternity Hospital — Level 4',
    ownership: 'private',
    category: 'maternity',
    address: 'Argwings Kodhek Road',
    county: 'Nairobi', subcounty: 'Kilimani',
    coords: { lat: -1.296, lng: 36.79 },
    phone: '+254 20 282 8000', whatsapp: '+254 719 071 000',
    verified: 'regulator_verified',
    rating: 4.2, reviewCount: 478,
    distanceKm: 5.1,
    insurance: ['NHIF', 'AAR', 'JUBILEE', 'CIC', 'BRITAM', 'MADISON', 'APA'],
    services: ['Antenatal', 'Delivery', 'C-section', 'Postnatal', 'Pediatric'],
    open: true, openLabel: 'Open 24 hours',
    photo: 'hospital',
    priceBand: 'KSh',
    waitMins: 28,
  },
];

const SERVICE_CATS = [
  { id: 'general', name: 'General consultation', sub: 'GP, primary care', icon: 'Stethoscope' },
  { id: 'maternity', name: 'Maternity', sub: 'Antenatal & delivery', icon: 'Baby' },
  { id: 'lab', name: 'Lab tests', sub: 'Blood, urine, imaging-prep', icon: 'Lab' },
  { id: 'dental', name: 'Dental', sub: 'Cleaning, fillings, ortho', icon: 'Tooth' },
  { id: 'pharmacy', name: 'Pharmacy', sub: 'Prescriptions & delivery', icon: 'Pill' },
  { id: 'radiology', name: 'X-ray & ultrasound', sub: 'Imaging & scans', icon: 'Lab' },
  { id: 'specialist', name: 'Specialist care', sub: 'Cardio, derm, ortho', icon: 'Stethoscope' },
  { id: 'emergency', name: 'Emergency', sub: '24-hour urgent care', icon: 'Cross' },
];

const INSURERS = [
  'NHIF / SHA', 'AAR Healthcare', 'Jubilee', 'CIC', 'Britam',
  'Madison', 'APA', 'Old Mutual', 'Liaison', 'Resolution',
];

const REVIEWS = [
  {
    id: 'r1', author: 'Wanjiru K.', date: '3 weeks ago',
    rating: 5, service: 'Maternity', insurance: 'yes_fully', provider: 'NHIF',
    aspects: { cleanliness: 5, staff: 5, wait: 4, value: 5 },
    text: 'Excellent antenatal care. Nurses were patient and answered every question. NHIF was accepted without issues — only paid for one private-room upgrade.',
    helpful: 24,
  },
  {
    id: 'r2', author: 'James M.', date: '1 month ago',
    rating: 4, service: 'General consultation', insurance: 'yes_partially', provider: 'AAR',
    aspects: { cleanliness: 5, staff: 4, wait: 3, value: 4 },
    text: 'Doctor was thorough. AAR covered the consult but lab tests had a co-pay we did not expect. Wait was around 40 minutes on a Tuesday morning.',
    helpful: 18,
  },
  {
    id: 'r3', author: 'Anonymous', date: '2 months ago',
    rating: 3, service: 'Emergency', insurance: 'no', provider: '',
    aspects: { cleanliness: 4, staff: 3, wait: 2, value: 3 },
    text: 'Came in at night with a child fever. Triage was slow. Once seen, treatment was good and clear. Paid cash — bill was steep.',
    helpful: 9,
  },
];

window.HC_DATA = { FACILITIES, SERVICE_CATS, INSURERS, REVIEWS };
